# This is the configuration for golangci-lint for the restic project.
#
# A sample config with all settings is here:
# https://github.com/golangci/golangci-lint/blob/master/.golangci.example.yml

version: "2"

linters:
  # only enable the linters listed below
  default: none
  enable:
    # make sure all errors returned by functions are handled
    - errcheck

    # detect improper error formatting and wrapping issues
    - errorlint

    # examine code and report suspicious constructs, such as Printf calls whose
    # arguments do not align with the format string
    - govet

    # make sure names and comments are used according to the conventions
    - revive

    # detect when assignments to existing variables are not used
    - ineffassign

    # run static analysis and find errors
    - staticcheck

    # find unused variables, functions, structs, types, etc.
    - unused
  exclusions:
    rules:
      - linters:
        - revive
        text: exported (function|method|var|type|const) .* should have comment or be unexported
      - linters:
        - revive
        text: don't use ALL_CAPS in Go names; use CamelCase

formatters:
  enable:
    # make sure code is formatted
    - gofmt
